#!/bin/bash
#
#Use this script to chroot into a rootfs generated by the nvidia rootfs generation scripts for the jetson xavier. This script can only be
#used on devices on the arm64/armv8 arch as it does not use any sort of qemu binaries.
#
#This script is mostly intended for making manual test edits to the rootfs to see if they work before adding them to the nvidia shell scripts.
#


echo "enter complete path to rootfs"
read rootfsdir
pushd "$rootfsdir" > /dev/null 2>&1

#sanity check
currentdir=$(pwd)
echo "$currentdir"

sudo mount /sys ./sys -o bind
sudo mount /proc ./proc -o bind
sudo mount /dev ./dev -o bind
sudo mount /dev/pts ./dev/pts -o bind

sudo LC_ALL=C chroot .
